[package]
name = "cprocessor"
version = "0.1.0"
authors = ["invin1 <marafat@bgsu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
